# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150906080247 on 2015-09-24 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencivicdata', '0002_add_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrelatedentity',
            old_name='vote',
            new_name='vote_event',
        ),
        migrations.RenameField(
            model_name='personvote',
            old_name='vote',
            new_name='vote_event',
        ),
        migrations.RenameField(
            model_name='votecount',
            old_name='vote',
            new_name='vote_event',
        ),
    ]
