# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-09-25 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opencivicdata', '0003_rename_vote_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sort_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='division',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='opencivicdata.Division'),
        ),
    ]
