# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencivicdata', '0005_add_agenda_item_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='person_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name='memberships', to='opencivicdata.Person'),
        ),
    ]
