# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencivicdata', '0008_auto_20170320_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestbase',
            options={'ordering': ('election', 'name'), 'verbose_name_plural': 'Contests (base objects)'},
        ),
        migrations.AddField(
            model_name='candidacy',
            name='registration_status',
            field=models.CharField(choices=[('filed', 'Filed'), ('qualified', 'Qualified'), ('withdrawn', 'Withdrawn'), ('write-in', 'Write-in')], help_text='Registration status of the candidate.', max_length=10, null=True),
        ),
    ]
