# Generated by Django 2.0.9 on 2018-10-29 15:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("legislative", "0006_billversion_extras")]

    operations = [
        migrations.AlterField(
            model_name="voteevent",
            name="extras",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        )
    ]
