# Generated by Django 2.2.3 on 2019-11-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("legislative", "0010_auto_20191031_1507")]

    operations = [
        migrations.AlterField(
            model_name="searchablebill",
            name="version_link",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searchable",
                to="legislative.BillVersionLink",
            ),
        )
    ]
