# Generated by Django 3.0.2 on 2020-01-03 14:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislative', '0011_auto_20191124_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdocument',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
