# Generated by Django 2.2.10 on 2020-03-26 04:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("legislative", "0012_billdocument_extras")]

    operations = [
        migrations.AddIndex(
            model_name="searchablebill",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_index"
            ),
        )
    ]
