# Generated by Django 2.2.3 on 2020-01-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0012_billdocument_extras"),
    ]

    operations = [
        migrations.AlterModelOptions(name="event", options={"managed": False},),
        migrations.AlterModelOptions(
            name="eventagendaitem", options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="eventagendamedia", options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="eventagendamedialink", options={"managed": False},
        ),
        migrations.AlterModelOptions(name="eventdocument", options={"managed": False},),
        migrations.AlterModelOptions(
            name="eventdocumentlink", options={"managed": False},
        ),
        migrations.AlterModelOptions(name="eventlink", options={"managed": False},),
        migrations.AlterModelOptions(name="eventlocation", options={"managed": False},),
        migrations.AlterModelOptions(name="eventmedia", options={"managed": False},),
        migrations.AlterModelOptions(
            name="eventmedialink", options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="eventparticipant", options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="eventrelatedentity", options={"managed": False},
        ),
        migrations.AlterModelOptions(name="eventsource", options={"managed": False},),
    ]
