# Generated by Django 2.2.3 on 2020-01-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0013_auto_20200109_2255"),
    ]

    operations = [
        migrations.RemoveField(model_name="eventagendaitem", name="event",),
        migrations.RemoveField(model_name="eventagendamedia", name="agenda_item",),
        migrations.RemoveField(model_name="eventagendamedialink", name="media",),
        migrations.RemoveField(model_name="eventdocument", name="event",),
        migrations.RemoveField(model_name="eventdocumentlink", name="document",),
        migrations.RemoveField(model_name="eventlink", name="event",),
        migrations.RemoveField(model_name="eventlocation", name="jurisdiction",),
        migrations.RemoveField(model_name="eventmedia", name="event",),
        migrations.RemoveField(model_name="eventmedialink", name="media",),
        migrations.RemoveField(model_name="eventparticipant", name="event",),
        migrations.RemoveField(model_name="eventparticipant", name="organization",),
        migrations.RemoveField(model_name="eventparticipant", name="person",),
        migrations.RemoveField(model_name="eventrelatedentity", name="agenda_item",),
        migrations.RemoveField(model_name="eventrelatedentity", name="bill",),
        migrations.RemoveField(model_name="eventrelatedentity", name="organization",),
        migrations.RemoveField(model_name="eventrelatedentity", name="person",),
        migrations.RemoveField(model_name="eventrelatedentity", name="vote_event",),
        migrations.RemoveField(model_name="eventsource", name="event",),
        migrations.DeleteModel(name="Event",),
        migrations.DeleteModel(name="EventAgendaItem",),
        migrations.DeleteModel(name="EventAgendaMedia",),
        migrations.DeleteModel(name="EventAgendaMediaLink",),
        migrations.DeleteModel(name="EventDocument",),
        migrations.DeleteModel(name="EventDocumentLink",),
        migrations.DeleteModel(name="EventLink",),
        migrations.DeleteModel(name="EventLocation",),
        migrations.DeleteModel(name="EventMedia",),
        migrations.DeleteModel(name="EventMediaLink",),
        migrations.DeleteModel(name="EventParticipant",),
        migrations.DeleteModel(name="EventRelatedEntity",),
        migrations.DeleteModel(name="EventSource",),
    ]
