# Generated by Django 4.1.3 on 2022-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0013_auto_20200326_0458"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
        migrations.AddField(
            model_name="voteevent",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
    ]
