# Generated by Django 4.1.7 on 2023-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legislative", "0015_auto_20221215_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlocation",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="eventlocation",
            name="longitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="classification",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="bill",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="bill",
            name="subject",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="billaction",
            name="classification",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="billaction",
            name="extras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="billdocument",
            name="extras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="billversion",
            name="extras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="event",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="eventagendaitem",
            name="classification",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="eventagendaitem",
            name="extras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="eventagendaitem",
            name="notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="eventagendaitem",
            name="subjects",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="voteevent",
            name="extras",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="voteevent",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="voteevent",
            name="motion_classification",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name="SearchableBill",
        ),
    ]
