# Generated by Django 2.2.3 on 2020-01-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="event", options={},),
        migrations.AlterModelOptions(name="eventagendaitem", options={},),
        migrations.AlterModelOptions(name="eventagendamedia", options={},),
        migrations.AlterModelOptions(name="eventagendamedialink", options={},),
        migrations.AlterModelOptions(name="eventdocument", options={},),
        migrations.AlterModelOptions(name="eventdocumentlink", options={},),
        migrations.AlterModelOptions(name="eventlink", options={},),
        migrations.AlterModelOptions(name="eventlocation", options={},),
        migrations.AlterModelOptions(name="eventmedia", options={},),
        migrations.AlterModelOptions(name="eventmedialink", options={},),
        migrations.AlterModelOptions(name="eventparticipant", options={},),
        migrations.AlterModelOptions(name="eventrelatedentity", options={},),
        migrations.AlterModelOptions(name="eventsource", options={},),
    ]
