# Generated by Django 2.2.3 on 2019-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_auto_20171005_2028")]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("legislature", "Legislature"),
                    ("executive", "Executive"),
                    ("upper", "Upper Chamber"),
                    ("lower", "Lower Chamber"),
                    ("party", "Party"),
                    ("committee", "Committee"),
                    ("commission", "Commission"),
                    ("corporation", "Corporation"),
                    ("agency", "Agency"),
                    ("department", "Department"),
                    ("judiciary", "Judiciary"),
                ],
                help_text="The type of Organization being defined.",
                max_length=100,
            ),
        )
    ]
