# Generated by Django 3.0.2 on 2020-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191124_1658'),
        ('core', '0005_auto_20191031_1507'),
    ]

    operations = [
    ]
