# Generated by Django 4.1.3 on 2022-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20200103_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="jurisdiction",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The last time this object was seen in a scrape.",
            ),
        ),
    ]
