# Generated by Django 4.1.7 on 2023-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20221215_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdiction",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="jurisdiction",
            name="feature_flags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of features that are present for data in this jurisdiction.",
            ),
        ),
        migrations.AlterField(
            model_name="jurisdiction",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="membership",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="organization",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="person",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="post",
            name="extras",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="A key-value store for storing arbitrary information not covered elsewhere.",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="locked_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
