# Generated by Django 3.2 on 2024-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221215_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='A key-value store for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='A key-value store for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='A key-value store for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='A key-value store for storing arbitrary information not covered elsewhere.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='extras',
            field=models.JSONField(blank=True, default=dict, help_text='A key-value store for storing arbitrary information not covered elsewhere.'),
        ),
    ]
