# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("elections", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="ballotmeasurecontest", options={"ordering": ("election", "name")}
        ),
        migrations.AlterModelOptions(
            name="candidatecontest", options={"ordering": ("election", "name")}
        ),
        migrations.AlterModelOptions(
            name="retentioncontest", options={"ordering": ("election", "name")}
        ),
    ]
