# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_auto_20170823_1648'),
        ('elections', '0004_election_fk'),
    ]

    operations = [
    ]
